# Generated by Django 6.0 on 2025-12-29 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='leagues/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='League.league')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='League.league')),
                ('first_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='League.team')),
                ('second_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='League.team')),
                ('third_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='League.team')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='League.league')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='accounts.profile')),
                ('first_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='League.team')),
                ('second_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='League.team')),
                ('third_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='League.team')),
            ],
            options={
                'unique_together': {('profile', 'league')},
            },
        ),
    ]
